// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/message.proto

package pbs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Register struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{1}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

func (m *Register) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Register) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Register) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterAck struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAck) Reset()         { *m = RegisterAck{} }
func (m *RegisterAck) String() string { return proto.CompactTextString(m) }
func (*RegisterAck) ProtoMessage()    {}
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{2}
}

func (m *RegisterAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAck.Unmarshal(m, b)
}
func (m *RegisterAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAck.Marshal(b, m, deterministic)
}
func (m *RegisterAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAck.Merge(m, src)
}
func (m *RegisterAck) XXX_Size() int {
	return xxx_messageInfo_RegisterAck.Size(m)
}
func (m *RegisterAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAck.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAck proto.InternalMessageInfo

func (m *RegisterAck) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterAck) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Login struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{3}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAck struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{4}
}

func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (m *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(m, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginAck) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserInfo struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoAck struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Error                *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoAck) Reset()         { *m = UserInfoAck{} }
func (m *UserInfoAck) String() string { return proto.CompactTextString(m) }
func (*UserInfoAck) ProtoMessage()    {}
func (*UserInfoAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8447775385e7eb85, []int{6}
}

func (m *UserInfoAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoAck.Unmarshal(m, b)
}
func (m *UserInfoAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoAck.Marshal(b, m, deterministic)
}
func (m *UserInfoAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoAck.Merge(m, src)
}
func (m *UserInfoAck) XXX_Size() int {
	return xxx_messageInfo_UserInfoAck.Size(m)
}
func (m *UserInfoAck) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoAck.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoAck proto.InternalMessageInfo

func (m *UserInfoAck) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfoAck) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfoAck) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "pbs.Error")
	proto.RegisterType((*Register)(nil), "pbs.Register")
	proto.RegisterType((*RegisterAck)(nil), "pbs.RegisterAck")
	proto.RegisterType((*Login)(nil), "pbs.Login")
	proto.RegisterType((*LoginAck)(nil), "pbs.LoginAck")
	proto.RegisterType((*UserInfo)(nil), "pbs.UserInfo")
	proto.RegisterType((*UserInfoAck)(nil), "pbs.UserInfoAck")
}

func init() { proto.RegisterFile("pb/message.proto", fileDescriptor_8447775385e7eb85) }

var fileDescriptor_8447775385e7eb85 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xe9, 0xd5, 0x4a, 0xef, 0x75, 0x91, 0xe0, 0x50, 0x9c, 0x42, 0xa6, 0x9b, 0x2a, 0xe8,
	0x2c, 0xa2, 0x70, 0x83, 0xe0, 0x14, 0x10, 0x5c, 0xd3, 0xf6, 0x59, 0xc2, 0xd9, 0x24, 0xbc, 0x57,
	0xf1, 0xdf, 0x97, 0x26, 0xd7, 0xe3, 0x10, 0x15, 0xe4, 0xb6, 0x7c, 0x49, 0xbe, 0x5f, 0x7e, 0x49,
	0xe0, 0x22, 0xb4, 0xd7, 0x23, 0x32, 0x9b, 0x01, 0x9b, 0x40, 0x7e, 0xf2, 0x22, 0x0f, 0x2d, 0xab,
	0x3b, 0x28, 0xb6, 0x44, 0x9e, 0x84, 0x80, 0xb3, 0xce, 0xf7, 0x58, 0x67, 0x32, 0xdb, 0x14, 0x3a,
	0x8e, 0x85, 0x84, 0xaa, 0x47, 0xee, 0xc8, 0x86, 0xc9, 0x7a, 0x57, 0xaf, 0x64, 0xb6, 0x59, 0xeb,
	0xe3, 0x29, 0xf5, 0x0a, 0xa5, 0xc6, 0xc1, 0xf2, 0x84, 0x24, 0xae, 0xa0, 0xfc, 0x60, 0x24, 0x67,
	0xc6, 0x44, 0x59, 0xeb, 0x43, 0x16, 0x97, 0x50, 0xe0, 0x68, 0xec, 0xfb, 0x9e, 0x91, 0xc2, 0xdc,
	0x08, 0x86, 0xf9, 0xd3, 0x53, 0x5f, 0xe7, 0xa9, 0xb1, 0x64, 0xb5, 0x85, 0x6a, 0x21, 0x3f, 0x74,
	0xbb, 0x19, 0x30, 0xf9, 0x1d, 0xba, 0x3d, 0x39, 0x05, 0x21, 0xa1, 0xc0, 0xd9, 0x3e, 0x62, 0xab,
	0x1b, 0x68, 0x42, 0xcb, 0x4d, 0xbc, 0x8f, 0x4e, 0x0b, 0xea, 0x1e, 0x8a, 0x67, 0x3f, 0x58, 0xf7,
	0xa7, 0xdd, 0xb1, 0xc7, 0xea, 0x9b, 0xc7, 0x23, 0x94, 0x11, 0x70, 0x8a, 0x84, 0x84, 0xf2, 0x85,
	0x91, 0x9e, 0xdc, 0x9b, 0xff, 0x99, 0xa1, 0x0c, 0x54, 0xcb, 0x8e, 0xf9, 0xa0, 0xff, 0x3f, 0xe5,
	0x41, 0x22, 0xff, 0x45, 0xa2, 0x3d, 0x8f, 0xbf, 0x7e, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x7b, 0x2f, 0xd8, 0x09, 0x02, 0x00, 0x00,
}
